openapi: 3.0.2
info:
  version: 0.0.1
  title: BlockRent API
  description: BlockRent API

paths:

  '/registrations/{registrationId}':
    get:
      summary: Get registration info
      tags:
        - registration
      parameters:
        - $ref: '#/components/parameters/registrationId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'

  '/registrations':
    post:
      summary: Submit registration form
      tags:
        - registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResponse'

  '/registrations/{registrationId}/signup':
    post:
      summary: Submit sign up form
      tags:
        - sign up
      parameters:
        - $ref: '#/components/parameters/registrationId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'

components:
  parameters:
    registrationId:
      in: path
      name: registrationId
      required: true
      schema:
        type: string

  schemas:

    Registration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/RegistrationType'
        personalDetails:
          $ref: '#/components/schemas/PersonalDetails'
        leaseApplicationDetails:
          $ref: '#/components/schemas/LeaseApplicationDetails'
        createdAt:
          type: string
          format: date

    RegistrationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/RegistrationType'
        personalDetails:
          $ref: '#/components/schemas/PersonalDetails'
        leaseApplicationDetails:
          $ref: '#/components/schemas/LeaseApplicationDetails'
        createdAt:
          type: string
          format: date

    RegistrationType:
      type: string
      enum:
        - TENANT
        - LANDLORD
        - PROPERTY_AGENT

    Application:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ApplicationStatus'
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date

    ApplicationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ApplicationStatus'
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date

    ApplicationStatus:
      type: string
      enum:
        - IN_PROGRESS
        - UNVERIFIED
        - VERIFIED

    PersonalDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        email:
          type: string

    LeaseApplicationDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        applicationId:
          type: string
        address:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        otherParty:
          $ref: '#/components/schemas/PersonalDetails'
