# Generated by Django 2.1.7 on 2019-02-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=128)),
                ('internal_id', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(max_length=512)),
                ('onwer_id', models.CharField(max_length=512)),
                ('application_address', models.CharField(max_length=256)),
                ('application_start_date', models.CharField(max_length=256)),
                ('application_end_date', models.CharField(max_length=64)),
                ('application_deposit_amount', models.CharField(max_length=128)),
                ('application_deposit_payment_terms', models.CharField(max_length=64)),
                ('application_status', models.CharField(max_length=128)),
                ('application_deposit_holding', models.CharField(max_length=64)),
                ('application_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=512)),
                ('event_status', models.CharField(max_length=512)),
                ('event_occured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('secret_key', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=512)),
                ('password_reset_token', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('user_type', models.CharField(max_length=64)),
                ('user_status', models.CharField(max_length=128)),
                ('user_bsb', models.CharField(max_length=64)),
                ('user_account_number', models.CharField(max_length=128)),
                ('user_bank_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField()),
            ],
        ),
    ]
