# Generated by Django 2.1.7 on 2019-02-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_deposit_amount',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_deposit_holding',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_deposit_payment_terms',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(default='NEW', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_account_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bank_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bsb',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('VERIFIED', 'VERIFIED'), ('SUSPENDED', 'SUSPENDED')], default='NEW', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TENANT', 'TENANT'), ('LANDLORD', 'LANDLORD'), ('AGENT', 'AGENT'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64),
        ),
    ]
