# Generated by Django 2.1.7 on 2019-02-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190219_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='819a<<', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='<<15e5', max_length=256),
        ),
    ]
