# Generated by Django 2.1.7 on 2019-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190219_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='1a70<<', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='<<9f04', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TENANT', 'TENANT'), ('LLANDLORD', 'LANDLORD'), ('AGENT', 'AGENT'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64),
        ),
    ]
