# Generated by Django 2.1.7 on 2019-02-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190219_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_owner_dispute_claim',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='application',
            name='application_tenant_dispute_claim',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('VERIFIED', 'VERIFIED'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DISPUTE', 'DISPUTE'), ('COMPLETE', 'COMPLETE')], default='NEW', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='internal_id',
            field=models.CharField(default='7efd', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('HANDLED', 'HANDLED'), ('IGNORED', 'IGNORED')], default='NEW', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='222d<<', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='<<ec25', max_length=256),
        ),
    ]
