# Generated by Django 2.1.7 on 2019-02-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190219_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='internal_id',
            field=models.CharField(default='7494', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='4a36<<', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='<<054c', max_length=256),
        ),
    ]
