# Generated by Django 2.1.7 on 2019-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190220_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant_type', models.CharField(choices=[('TENANT', 'TENANT'), ('LANDLORD', 'LANDLORD'), ('AGENT', 'AGENT'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64)),
                ('registrant_first_name', models.DateTimeField(blank=True)),
                ('registrant_last_name', models.DateTimeField(blank=True)),
                ('registrant_phone', models.DateTimeField(blank=True)),
                ('registrant_email', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='application_id',
            new_name='ejari_no',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='onwer_id',
            new_name='owner_id',
        ),
        migrations.AddField(
            model_name='application',
            name='premise_no',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='internal_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='a405<<', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='<<7614', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TENANT', 'TENANT'), ('LANDLORD', 'LANDLORD'), ('AGENT', 'AGENT'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64),
        ),
    ]
