# Generated by Django 2.1.7 on 2019-02-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190225_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='FFFF', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='FFFF', max_length=256),
        ),
    ]
